### ISSUE TITLE
ZEUR fiat currency throwing exception

### ISSUE THREAD

**Issue by nicwn** [AUGMXNT/perfi#1]
```
Importing...
Traceback (most recent call last):
  File "/Users/nick/Documents/perfi/bin/import_from_exchange.py", line 107, in <module>
    main()
  File "/Users/nick/Documents/perfi/bin/import_from_exchange.py", line 97, in main
    importer.do_import(
  File "/Users/nick/Documents/perfi/perfi/ingest/exchange.py", line 345, in do_import
    txns = self.ledgers_csv_to_chain_txns(
  File "/Users/nick/Documents/perfi/perfi/ingest/exchange.py", line 207, in ledgers_csv_to_chain_txns
    asset_tx_id = self.get_symbol(asset).lower()
  File "/Users/nick/Documents/perfi/perfi/ingest/exchange.py", line 179, in get_symbol
    raise Exception(
Exception: This asset code in Kraken represents a fiat currency that we don't know how to convert prices for yet. Don't know what to do so throwing exception. Asset: ZEUR
```

**Comment by peloriante** [comment]
Fixed with commit 7b49ed85cbb12c588aef014ee8ba03d04722ebcf

@nicwn  would you mind pulling latest and trying again?

**Comment by nicwn** [comment]
git pull

```
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 10 (delta 7), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/AUGMXNT/perfi
   1c580de..7b49ed8  main       -> origin/main
Updating 1c580de..7b49ed8
Fast-forward
 README.md                 |   2 +
 bin/map_assets.py         |  37 ++-
 perfi/constants/assets.py | 665 ++++++++++++++++++++++++----------------------
 3 files changed, 360 insertions(+), 344 deletions(-)
```

rerun and still got this:

```
Address already seems to exist: kraken.kraken1
Importing...
Traceback (most recent call last):
  File "/Users/nick/Documents/perfi/bin/import_from_exchange.py", line 107, in <module>
    main()
  File "/Users/nick/Documents/perfi/bin/import_from_exchange.py", line 97, in main
    importer.do_import(
  File "/Users/nick/Documents/perfi/perfi/ingest/exchange.py", line 345, in do_import
    txns = self.ledgers_csv_to_chain_txns(
  File "/Users/nick/Documents/perfi/perfi/ingest/exchange.py", line 207, in ledgers_csv_to_chain_txns
    asset_tx_id = self.get_symbol(asset).lower()
  File "/Users/nick/Documents/perfi/perfi/ingest/exchange.py", line 179, in get_symbol
    raise Exception(
Exception: This asset code in Kraken represents a fiat currency that we don't know how to convert prices for yet. Don't know what to do so throwing exception. Asset: ZEUR
```

**Comment by nicwn** [comment]
Success! Thanks.

```
(perfi) nick@Nicholass-iMac-Pro perfi % poetry run python bin/import_from_exchange.py --entity_name Nick --file /Users/nick/Downloads/Kraken\ 2021\ ledgers.csv --exchange kraken --exchange_account_id kraken1
Address already seems to exist: kraken.kraken1
Importing...
Saving unified txs to db: 100%|████████████████| 86/86 [00:00<00:00, 948.55it/s]
Done.
```
